import random
from game.dice import Dice
from game.scoreboard import Scoreboard
import numpy as np

class Yatzy:

    """
        Implements Yatzy game functionality

        Args:
            lock_list: List of which dice to keep
            printouts: Set printouts on or off for troubleshooting
            dice: List of the five current dice
            scoreboard: Scoreboard for the game to track scores
            rolls_left: Rerolls left for the current round (3 rolls per round)
            reward: Reward gotten for the last action
            done: Flag to indicate the game has ended
            next_state: variable to hold the next gamestate
            final_score: Final score achieved after game has ended
            upper_sum: Current sum of the upper section
            info: Variable for info about the game after game ends
            print: Printout flag

    """ 

    def __init__(self):
        self.state = True
        self.lock_list = np.array([0,0,0,0,0])
        self.printouts = False
        self.dice = Dice()
        self.dice.initialize()
        self.scoreboard = Scoreboard()
        self.scoreboard.initialize()
        self.rolls_left = 2
        self.reward = 0
        self.done = 0
        self.next_state = None
        self.final_score = 0
        self.upper_sum = 0
        self.info = 0
        self.print = False
       
    def reset(self):
        """
        Resets the game back to default state 
        """  
        self.state = True
        self.lock_list = np.array([0,0,0,0,0])
        self.dice.initialize()
        self.scoreboard.initialize()
        self.rolls_left = 2
        self.reward = 0
        self.done = False
        self.next_state = None
        self.final_score = 0
        self.upper_sum = 0
        self.info = 0
        
        return (tuple(self.dice.display()), self.rolls_left, tuple(self.scoreboard.get_scoreboard_mask()))
    
    def step(self, action):
        
        """
        Evolves the game with the given action

        Args:
            action: action taken by the playing agent

        Returns:
            next_state: Next state of the game after the action taken
            reward: Reward gotten from the action
            done: flag if game is finished
            final_score: Final score when game is finished
            info: information about game for statistics tracking
        """  

        if action[0] == "reroll":
            self.rolls_left -= 1
            if self.rolls_left < 0:
                raise ValueError('rolls_left went negative!')
            
            old_dice = self.dice.display()

         
            lock_mask = action[1]
            self.dice.lock(lock_mask)
            self.dice.reroll()

        elif action[0] == "score":
            placement = action[1]
            self.scoreboard.place_score(self.dice, placement)
            self.dice.lock([0,0,0,0,0])
            self.dice.reroll()
            self.rolls_left = 2
            old_dice = self.dice.display()

        self.generate_reward(action, old_dice)
        
        self.check_if_game_over()

        #Is bellman working correctly at the end of the game?
        self.next_state = (tuple(self.dice.display()), self.rolls_left, tuple(self.scoreboard.get_scoreboard_mask()))

        return self.next_state, self.reward, self.done, self.final_score, self.info

    def generate_reward(self, action, old_dice):
        
        """
        Generate a reward for the agent given their action

        Args:
            action: action taken by the playing agent
            old_dice: dice before the action was taken

        Returns:
            reward: Reward generated by the action taken
        """  

        self.reward = 0

        if action[0] == "score":
            
            self.reward += self.scoreboard.place_score(self.dice, action[1]) / 10

            if self.reward == 0:
                self.reward = -1

        self.reward += 0.1 * (self.dice_strength(self.dice.display()) - self.dice_strength(old_dice))

        bonus_status, upper_sum, bonus_points = self.scoreboard.get_upper_sum()

        self.reward += (upper_sum - self.upper_sum) * 0.1

        self.upper_sum = upper_sum

        self.reward += bonus_points


    def dice_strength(self, dice):

        """
        heuristic to score dice strength

        Args:
            dice: current dice

        Returns:
            score: value of how strong the dice are
        """  

        dice_counts = self.dice_to_dice_counts(dice)

        score = 0

        max_count = max(dice_counts)
        score += max_count * 5

        for i, count in enumerate(dice_counts):
            value = i + 1
            score += count * value

        return score


    def dice_to_dice_counts(self, dice):
        """
        Counts how many of each value of dice there are

        Args:
            dice: current dice

        Returns:
            count of how many dice of each value there are
        """  
        return np.bincount(dice, minlength=7)[1:]


    def check_if_game_over(self):

        """
        Checks if scoreboard is full hence game is now over
        """  

        scoreboard_mask = self.scoreboard.get_scoreboard_mask()
        
        if sum(scoreboard_mask) == len(scoreboard_mask):
            self.done = True
            self.final_score = self.scoreboard.score_game()
            self.reward += self.final_score[0] * 0.5
            self.info = 0
            

    def set_prints_on(self):
        """
        Set prints on for troubleshooting

        """  
        self.print = True